# Copyright 2018 Therp BV <https://therp.nl>
# Copyright 2022 Hunki Enterprises BV <https://hunki-enterprises.com>
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).
import logging

from odoo import api, models

_logger = logging.getLogger(__name__)


class MailThread(models.AbstractModel):
    _inherit = "mail.thread"

    @api.model
    def _message_route_process(self, message, message_dict, routes):
        # Set context key to suppress notification for autogenerated incoming mails
        if self._message_route_process_autoreply(message, message_dict, routes):
            _logger.info(
                "Ignoring email %s from %s because it seems to be an auto reply",
                message.get("Message-ID"),
                message.get("From"),
            )
            self = self.with_context(mail_autogenerated_header=message)
        return super()._message_route_process(
            message,
            message_dict,
            routes,
        )

    def _notify_thread(self, message, msg_vals=False, **kwargs):
        # Inhibit notifications if this is the notification for an incoming
        # autogenerated mail from another system
        if self.env.context.get("mail_autogenerated_header"):
            return []
        return super()._notify_thread(message, msg_vals=msg_vals, **kwargs)

    @api.model
    def _message_route_process_autoreply(self, message, message_dict, routes):
        """Determine if some message is an autoreply"""
        auto_submitted = message.get("Auto-Submitted")
        auto_response_suppress = message.get("X-Auto-Response-Suppress")
        return (
            auto_submitted
            and auto_submitted != "no"
            or auto_response_suppress
            and set(auto_response_suppress.split(", ")) & set(["AutoReply", "All"])
        )
